os: osx
language: r
r: 3.6.1
#cache: packages
before_install: 
  - "git clone --branch=MacOS-Original https://github.com/jasp-stats/jasp-required-files.git ~/pkgs"
  - cd Tests/R/tests/
install:
  - rm '/usr/local/bin/gfortran'
  - brew install jags
  - R < install.R --no-save
script:
  - R < testthat.R --no-save
env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - VDIFFR_RUN_TESTS=true
    #- R_LIBS_USER=~/pkgs/Frameworks/R.framework/Versions/3.6/Resources/library
