name: 'Ubuntu'

on:
   pull_request:
     paths: ['**.cpp', '**.h', '**.R', '**.cmake', '**.txt', '**.in', '**.yml']
   workflow_dispatch:

jobs:
      
   build-jasp:
   
    runs-on: ubuntu-latest
    env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Install Qt6
        uses: jurplel/install-qt-action@v3
        with:
            version: 6.7.0
            aqtversion: '==3.1.*'
            host: 'linux'
            target: 'desktop'
            arch: 'linux_gcc_64'
            cache: 'true'
            modules: 'qtpositioning qtwebchannel qtwebengine qtwebsockets qtwebview debug_info qt5compat qtshadertools qtwaylandcompositor'
            tools: 'tools_qtcreator,qt.tools.qtcreator tools_cmake tools_ninja'
            
      - name: Install dependencies of build system
        run: |     
            sudo apt install libboost-dev libjsoncpp25 libjsoncpp-dev libarchive13 libarchive-dev
            sudo apt install libxcb-xkb-dev libxcb-xkb1 libxcb-xinerama0 libxkbcommon-dev libxkbcommon-x11-dev autoconf zlib1g zlib1g-dev cmake
            sudo apt install gfortran build-essential flex libssl-dev libgl1-mesa-dev libsqlite3-dev r-base
            sudo apt install libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev #required by some r packgaes
            sudo apt install libcurl4-openssl-dev #required by curl R packages
            sudo apt install libmpfr-dev #required by rmpfr packages
            sudo apt install libglpk-dev #required by igraph packages
            sudo apt install jags
            sudo apt install libminizip-dev # required by freexl
            git clone https://github.com/jasp-stats/freexl.git
            cd freexl && ./configure && make && sudo make install
            
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.83.0
            platform_version: 22.04

      - name: Install Readstat
        run: |
            wget https://github.com/WizardMac/ReadStat/releases/download/v1.1.9/readstat-1.1.9.tar.gz
            tar -xzf readstat-*.tar.gz && cd readstat-*/
            ./configure
            make
            sudo make install
        
      - name: Configure JASP desktop
        run: |
            git submodule update --init
            cmake -S . -B jasp-build -DJASP_TEST_BUILD=ON
        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
            Boost_INCLUDE_DIR: "${{steps.install-boost.outputs.BOOST_ROOT}}/include"
            Boost_LIBRARY_DIRS: "${{steps.install-boost.outputs.BOOST_ROOT}}/lib"

      - name: Build JASP desktop
        run: |
            cmake --build jasp-build --target all
